# Generated by Django 2.0.7 on 2018-09-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(upload_to='resource/%Y/%m', verbose_name='资源文件'),
        ),
    ]
