# Generated by Django 2.0.7 on 2018-09-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_vidio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='needknow',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='tips',
            field=models.CharField(default='', max_length=300, verbose_name='学习要点'),
        ),
    ]
